//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by RESOURCE.RC
//
#define IDI_APPICON                     100
#define IDR_ACCELERATOR                 101
#define IDD_MAINDIALOG                  102
#define IDD_ABOUTDIALOG                 103
#define IDR_APPMENU                     104
#define ID_HELP_ABOUT                   200
#define ID_CONNECT                      201
#define ID_QUIT                         202
#define ID_ABOUT                        204
#define IDC_MSGINPUT                    1002
#define IDC_EDIT2                       1003
#define IDC_SENDBTN                     1004
#define IDC_CORYRIGHT                   1005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         205
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
